---
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}.rpm"
- name: Install vector packages
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}.rpm
    disable_gpg_check: True
  notify: Start Vector service

- name: Create vector config file
  ansible.builtin.template:
    src: vector.yml.j2
    dest: "/etc/vector/vector.yml"
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Vector systemd unit
  ansible.builtin.template:
    src: vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    backup: true
  notify: Start Vector service
