---
dependency:
  name: galaxy
driver:
  name: docker
platforms:  
  - name: Ubuntu_latest
    image: ubuntu:latest
    dockerfile: Dockerfile
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false

#   - name: C8
#     image: quay.io/centos/centos:stream8
#     command: /sbin/init
#     privileged: True
