---
dependency:
  name: galaxy
driver:
  name: docker
platforms:  
  - name: Ubuntu
    image: ubuntu:latest
    dockerfile: Dockerfile
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
